-- Hyprland config, Lua format.
-- hyprlang (.conf) is deprecated since 0.55 and is removed in 0.57.
-- Refer to the wiki: https://wiki.hypr.land/Configuring/Start/

-- Machine-local files. pcall so a missing one doesn't kill the rest of the config.
pcall(require, "theme")    -- generated by aether (accent colors)
pcall(require, "monitors") -- per-machine monitor layout

--################
--### MONITORS ###
--################

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- hyprctl monitors all
-- Fallback for any monitor not matched in monitors.lua
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

--###################
--### MY PROGRAMS ###
--###################

local terminal    = "ghostty"
local fileManager = "nautilus"
local browser     = "chromium"
local editor      = "code"
local discord     = "vesktop"
local menu        = "tofi-drun -c ~/.config/tofi/configA --drun-launch=true"

--#################
--### AUTOSTART ###
--#################

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/
-- hyprland.start fires once, so this is the equivalent of the old exec-once.
hl.on("hyprland.start", function()
    -- Activates graphical-session.target, which xdg-desktop-portal declares as a
    -- Requisite. Without it the portal fails instantly and screen sharing is dead.
    -- Target unit lives in .config/systemd/user/hyprland-session.target.
    hl.exec_cmd("systemctl --user start hyprland-session.target")

    hl.exec_cmd("waybar")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("playerctld daemon")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("udiskie")
    hl.exec_cmd("omenix")
    -- hl.exec_cmd("hyprlock")

    -- open programs on specific workspaces
    hl.exec_cmd(browser, { workspace = "1 silent" })
    hl.exec_cmd(discord, { workspace = "3 silent" })
end)

-- Top-level calls re-run on every config reload, like the old `exec`.
-- dark theme
hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita'")
hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'default'")
hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Classic'")

--#############################
--### ENVIRONMENT VARIABLES ###
--#############################

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("HYPRCURSOR_SIZE", "24")
-- https://discord.com/channels/961691461554950145/1216066899729977435/1216076659552424107
-- mkdir -p ~/.local/share/icons && tar -xzf HyprBibataModernClassicSVG.tar.gz -C ~/.local/share/icons/
hl.env("HYPRCURSOR_THEME", "HyprBibataModernClassicSVG")

hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_STYLE_OVERRIDE", "kvantum")

-- Toolkit Backend Variables
hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("CLUTTER_BACKEND", "wayland")

-- XDG Specifications
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

--#####################
--### LOOK AND FEEL ###
--#####################

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in     = 1,
        gaps_out    = 0,
        border_size = 1,

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before turning this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding = 15,

        -- Change transparency of focused and unfocused windows
        -- Focused window is fully opaque; per-app exceptions below keep transparency
        active_opacity   = 1.0,
        inactive_opacity = 0.8,

        blur = {
            enabled = true,
            size    = 5,
            passes  = 2,
        },
    },

    animations = {
        enabled = true,
    },
})

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("myBezier", { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.05} } })
hl.curve("liner",    { type = "bezier", points = { {1, 1},      {1, 1}      } })

hl.animation({ leaf = "windows",    enabled = true,  speed = 3,   bezier = "default" })
-- hl.animation({ leaf = "border",      enabled = true, speed = 10, bezier = "default" })
-- hl.animation({ leaf = "borderangle", enabled = true, speed = 30, bezier = "liner", style = "loop" })
hl.animation({ leaf = "fade",       enabled = true,  speed = 5,   bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = false })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        -- pseudotile master switch was removed in Hyprland 0.55; pseudotiling is
        -- toggled via the pseudo dispatcher (mainMod + P below)
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

hl.config({
    misc = {
        force_default_wallpaper = -1,   -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = true, -- If true disables the random hyprland logo / anime girl background. :(
    },
})

--#############
--### INPUT ###
--#############

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity        = 0, -- -1.0 - 1.0, 0 means no modification.
        numlock_by_default = true,

        touchpad = {
            natural_scroll = true,
            scroll_factor  = 0.4,
        },
    },

    cursor = {
        hide_on_key_press = true,
    },
})

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Gestures/
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name          = "razer-razer-viper-mini",
    sensitivity   = -0.2,
    accel_profile = "flat",
})

--####################
--### KEYBINDINGSS ###
--####################

-- See https://wiki.hypr.land/Configuring/Basics/Binds/
local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + Q",      hl.dsp.window.close())
hl.bind(mainMod .. " + W",      hl.dsp.window.close())
hl.bind(mainMod .. " + M",      hl.dsp.exit())
hl.bind(mainMod .. " + E",      hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + R",      hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + B",      hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + C",      hl.dsp.exec_cmd(editor))
hl.bind(mainMod .. " + F",      hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + P",      hl.dsp.window.pseudo()) -- dwindle
hl.bind(mainMod .. " + S",      hl.dsp.exec_cmd("systemctl suspend"))
hl.bind(mainMod .. " + G",      hl.dsp.window.float())

-- Move focus with mainMod + arrow keys
hl.bind("ALT + home", hl.dsp.focus({ direction = "left" }))
hl.bind("ALT + end",  hl.dsp.focus({ direction = "right" }))
-- hl.bind("ALT + pageup", hl.dsp.focus({ direction = "up" }))
-- hl.bind("ALT + down",   hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

hl.bind(mainMod .. " + TAB",         hl.dsp.focus({ workspace = 10 }))
hl.bind(mainMod .. " + SHIFT + TAB", hl.dsp.window.move({ workspace = 10 }))

hl.bind("CTRL + ALT + " .. mainMod .. " + SHIFT + 1", hl.dsp.workspace.move({ monitor = 0 }))
hl.bind("CTRL + ALT + " .. mainMod .. " + SHIFT + 2", hl.dsp.workspace.move({ monitor = 1 }))

-- Example special workspace (scratchpad)
-- hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
-- hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Volume and Media Control
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true, locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { repeating = true, locked = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioPlay",        hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioNext",        hl.dsp.exec_cmd("playerctl next"))
hl.bind("XF86AudioPrev",        hl.dsp.exec_cmd("playerctl previous"))

-- Screen brightness
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl s +5%"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 5%-"))

hl.bind(mainMod .. " + K",         hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + L",         hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("hyprpicker --autocopy"))
hl.bind(mainMod .. " + PERIOD",    hl.dsp.exec_cmd("tofi-emoji -c ~/.config/tofi/configV --fuzzy-match true"))

-- clipboard
hl.bind("SUPER + V",         hl.dsp.exec_cmd("cliphist list | tofi -c ~/.config/tofi/configV | cliphist decode | wl-copy"))
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("hyprshot -m region --freeze --output-folder ~/ss"))
hl.bind("PRINT",             hl.dsp.exec_cmd("hyprshot -m region --freeze --output-folder ~/ss"))

-- notifications
hl.bind("SUPER + SHIFT + N", hl.dsp.exec_cmd("dunstctl history-pop"))
hl.bind("SUPER + N",         hl.dsp.exec_cmd("dunstctl close-all"))

--##############################
--### WINDOWS AND WORKSPACES ###
--##############################

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Keep transparency on these even when focused (exceptions to active_opacity = 1.0)
hl.window_rule({
    match   = { title = "(.*)(- Visual Studio Code)" },
    opacity = "0.85 override 0.8 override",
})

hl.window_rule({
    match   = { class = "^(com\\.mitchellh\\.ghostty)$" },
    opacity = "0.95 override 0.8 override",
})

hl.window_rule({
    match           = { class = "^(com\\.obsproject\\.Studio)$" },
    no_screen_share = true,
})

hl.window_rule({
    name  = "share-picker",
    match = { class = "^(ch\\.wysbd\\.hyprland-preview-share-picker)$" },

    float  = true,
    center = true,
    size   = {1000, 500},
})

hl.layer_rule({
    match           = { namespace = "notifications" },
    no_screen_share = true,
})
